/*
 * Copyright 2025 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.prethink.table;

import lombok.Value;
import org.openrewrite.Column;
import org.openrewrite.DataTable;
import org.openrewrite.Recipe;

/**
 * Registry of available context files generated by Moderne Prethink.
 */
public class ContextRegistry extends DataTable<ContextRegistry.Row> {

    public ContextRegistry(Recipe recipe) {
        super(recipe, "Context registry",
                "Registry of available context files for coding agents.");
    }

    @Value
    public static class Row {
        @Column(displayName = "Display name",
                description = "The display name of the context.")
        String displayName;

        @Column(displayName = "Short description",
                description = "A brief description of what context this provides.")
        String shortDescription;

        @Column(displayName = "Context file",
                description = "Path to the markdown file describing this context.")
        String contextFile;
    }
}
